# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/orderbook.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/orderbook.proto\x12\torderbook\"-\n\tOrderBook\x12 \n\x06orders\x18\x01 \x03(\x0b\x32\x10.orderbook.Order\"B\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08quantity\x18\x03 \x01(\x01\x12\x0c\n\x04side\x18\x04 \x01(\t\"\x07\n\x05\x45mpty2J\n\x10OrderBookService\x12\x36\n\x0cGetOrderBook\x12\x10.orderbook.Empty\x1a\x14.orderbook.OrderBookb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.orderbook_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERBOOK']._serialized_start=36
  _globals['_ORDERBOOK']._serialized_end=81
  _globals['_ORDER']._serialized_start=83
  _globals['_ORDER']._serialized_end=149
  _globals['_EMPTY']._serialized_start=151
  _globals['_EMPTY']._serialized_end=158
  _globals['_ORDERBOOKSERVICE']._serialized_start=160
  _globals['_ORDERBOOKSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
