# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import orderbook_pb2 as proto_dot_orderbook__pb2


class OrderBookServiceStub(object):
    """The OrderBookService service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrderBook = channel.unary_unary(
                '/orderbook.OrderBookService/GetOrderBook',
                request_serializer=proto_dot_orderbook__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_orderbook__pb2.OrderBook.FromString,
                )


class OrderBookServiceServicer(object):
    """The OrderBookService service definition
    """

    def GetOrderBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBook,
                    request_deserializer=proto_dot_orderbook__pb2.Empty.FromString,
                    response_serializer=proto_dot_orderbook__pb2.OrderBook.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderbook.OrderBookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderBookService(object):
    """The OrderBookService service definition
    """

    @staticmethod
    def GetOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderbook.OrderBookService/GetOrderBook',
            proto_dot_orderbook__pb2.Empty.SerializeToString,
            proto_dot_orderbook__pb2.OrderBook.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
